apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: minikube-backend-img:1.0
        ports:
        - containerPort: 8090
