---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: fo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fo
  template:
    metadata:
      labels:
        app: fo
    spec:
      containers:
      - image: minikube-frontend-img:1.0
        name: frontend
        ports:
        - containerPort: 80
